extends: google
parser: babel-eslint
rules:
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: false
        MethodDefinition: false
        ClassDeclaration: false
        ArrowFunctionExpression: false
        FunctionExpression: false
  semi:
    - 0
    - always
